from dataVisualization2 import net, get_module_id, get_skill_id

net.add_edge(get_module_id("LANG501a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG501a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG501a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("SHES501a"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("SHES501a"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("SHES501a"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("SHES501a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("SHES501a"), get_skill_id("TC-2.3"), weight=1)

net.add_edge(get_module_id("SHES505"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-4.1"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-4.3"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("SHES505"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("DDRS501"), get_skill_id("IDU-3.2"), weight=1)
net.add_edge(get_module_id("DDRS501"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("DDRS501"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("DDRS501"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("DDRS501"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("DDRS501"), get_skill_id("TC-3.4"), weight=1)

net.add_edge(get_module_id("EASI501a"), get_skill_id("IDU-3.2"), weight=1)

net.add_edge(get_module_id("INFO501a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO501a"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("INFO501a"), get_skill_id("TC-1.3"), weight=1)

net.add_edge(get_module_id("INFO502a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO502a"), get_skill_id("IDU-2.2"), weight=1)
net.add_edge(get_module_id("INFO502a"), get_skill_id("IDU-2.3"), weight=1)

net.add_edge(get_module_id("MATH500a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("MATH500a"), get_skill_id("TC-1.3"), weight=1)

net.add_edge(get_module_id("MATH501a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("MATH501a"), get_skill_id("TC-1.3"), weight=1)

net.add_edge(get_module_id("EASI541b"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("EASI541b"), get_skill_id("IDU-4.1"), weight=1)

net.add_edge(get_module_id("ISOC531"), get_skill_id("IDU-3.1"), weight=1)
net.add_edge(get_module_id("ISOC531"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("ISOC531"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("ISOC531"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("ISOC531"), get_skill_id("TC-2.2"), weight=1)

net.add_edge(get_module_id("MATH531"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("MATH531"), get_skill_id("IDU-1.2"), weight=1)

net.add_edge(get_module_id("PROJ531"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("PROJ531"), get_skill_id("IDU-4.1"), weight=1)

# semestre 7
net.add_edge(get_module_id("LANG701a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG701a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG701a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("LANG702a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG702a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG702a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("SHES703a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("SHES703a"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("SHES703a"), get_skill_id("TC-2.3"), weight=1)

net.add_edge(get_module_id("SHES704a"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("SHES704a"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("SHES704a"), get_skill_id("TC-3.4"), weight=1)
net.add_edge(get_module_id("SHES704a"), get_skill_id("TC-4.3"), weight=1)
net.add_edge(get_module_id("SHES704a"), get_skill_id("TC-4.4"), weight=1)

net.add_edge(get_module_id("DATA731a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("DATA731a"), get_skill_id("IDU-2.2"), weight=1)

net.add_edge(get_module_id("INFO731a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO731a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("INFO731a"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO731a"), get_skill_id("IDU-4.2"), weight=1)

net.add_edge(get_module_id("MATH741c"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("MATH741c"), get_skill_id("IDU-2.2"), weight=1)
net.add_edge(get_module_id("MATH741c"), get_skill_id("IDU-2.3"), weight=1)

net.add_edge(get_module_id("INFO732a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO732a"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("INFO732a"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("INFO732a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("INFO732a"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO732a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("INFO743c"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("INFO743c"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO743c"), get_skill_id("IDU-4.2"), weight=1)
net.add_edge(get_module_id("INFO743c"), get_skill_id("TC-1.3"), weight=1)

net.add_edge(get_module_id("PROJ731a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ731a"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("PROJ731a"), get_skill_id("IDU-4.1"), weight=1)

net.add_edge(get_module_id("DATA732a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("DATA732a"), get_skill_id("IDU-2.1"), weight=1)

net.add_edge(get_module_id("INFO734a"), get_skill_id("IDU-1.1"), weight=1)

net.add_edge(get_module_id("ISOC731a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("ISOC731a"), get_skill_id("IDU-3.2"), weight=1)
net.add_edge(get_module_id("ISOC731a"), get_skill_id("IDU-4.2"), weight=1)
net.add_edge(get_module_id("ISOC731a"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("ISOC731a"), get_skill_id("TC-1.3"), weight=1)
net.add_edge(get_module_id("ISOC731a"), get_skill_id("TC-3.2"), weight=1)

# Semestre 9
net.add_edge(get_module_id("LANG901a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG901a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG901a"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("LANG902a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG902a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG902a"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-1.3"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-4.1"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-4.2"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-4.3"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("PROJ901a"), get_skill_id("TC-4.4"), weight=1)
net.add_edge(get_module_id("SHES901a"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("SHES901a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("SHES901a"), get_skill_id("TC-3.4"), weight=1)
net.add_edge(get_module_id("SHES901a"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("SHES901a"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("IDU-2.2"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("IDU-3.1"), weight=1)
net.add_edge(get_module_id("INFO931"), get_skill_id("IDU-3.2"), weight=1)
net.add_edge(get_module_id("INFO932"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO932"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("INFO932"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("INFO932"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("PROJ931"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ931"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("PROJ931"), get_skill_id("IDU-3.1"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("IDU-3.1"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("DATA931"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("ISOC931"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("ISOC931"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("ISOC931"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("ISOC931"), get_skill_id("TC-4.1"), weight=1)
net.add_edge(get_module_id("PROJ932"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ932"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("PROJ932"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("PROJ932"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("PROJ932"), get_skill_id("IDU-4.1"), weight=1)

# Semestre 10
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-3.4"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-1.3"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-4.3"), weight=1)
net.add_edge(get_module_id("PROJ001"), get_skill_id("TC-4.4"), weight=1)

# semestre 6
net.add_edge(get_module_id("LANG601a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG601a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG601a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("PROJ601a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("PROJ601a"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("PROJ601a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("PROJ601a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("SHES601a"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("SHES602a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("INFO631a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO631a"), get_skill_id("IDU-1.2"), weight=1)

net.add_edge(get_module_id("MATH641c"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("MATH641c"), get_skill_id("IDU-2.3"), weight=1)

net.add_edge(get_module_id("PROJ631a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("PROJ631a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("PROJ631a"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("PROJ631a"), get_skill_id("TC-4.1"), weight=1)
net.add_edge(get_module_id("PROJ631a"), get_skill_id("TC-4.2"), weight=1)

net.add_edge(get_module_id("INFO632"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO632"), get_skill_id("IDU-4.1"), weight=1)

net.add_edge(get_module_id("INFO641c"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO641c"), get_skill_id("IDU-4.1"), weight=1)

net.add_edge(get_module_id("INFO642c"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO642c"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO642c"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("INFO642c"), get_skill_id("IDU-2.2"), weight=1)

net.add_edge(get_module_id("ISOC631"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("ISOC631"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("ISOC631"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("ISOC631"), get_skill_id("TC-1.4"), weight=1)

net.add_edge(get_module_id("PROJ632"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ632"), get_skill_id("IDU-2.1"), weight=1)

net.add_edge(get_module_id("INFO632a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO632a"), get_skill_id("IDU-4.1"), weight=1)

net.add_edge(get_module_id("ISOC631a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("ISOC631a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("ISOC631a"), get_skill_id("TC-1.1"), weight=1)

net.add_edge(get_module_id("PROJ632a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ632a"), get_skill_id("IDU-2.1"), weight=1)

# semestre 8
net.add_edge(get_module_id("LANG801a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG801a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG801a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("LANG802a"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("LANG802a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("LANG802a"), get_skill_id("TC-3.3"), weight=1)

net.add_edge(get_module_id("SHES802a"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("SHES802a"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("SHES802a"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("SHES802a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("SHES803a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-1.1"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-1.3"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-1.4"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-1.5"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-2.1"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-2.2"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-2.3"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-3.3"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-3.4"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-4.1"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-4.2"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-4.3"), weight=1)
net.add_edge(get_module_id("PROJ801"), get_skill_id("TC-4.4"), weight=1)

net.add_edge(get_module_id("DATA831a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("DATA831a"), get_skill_id("IDU-1.3"), weight=1)

net.add_edge(get_module_id("DATA832a"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("DATA832a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("DATA832a"), get_skill_id("IDU-2.2"), weight=1)
net.add_edge(get_module_id("DATA832a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("DATA832a"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("DATA832a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("INFO831a"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("INFO831a"), get_skill_id("IDU-2.1"), weight=1)
net.add_edge(get_module_id("INFO831a"), get_skill_id("IDU-2.2"), weight=1)
net.add_edge(get_module_id("INFO831a"), get_skill_id("IDU-3.1"), weight=1)
net.add_edge(get_module_id("INFO831a"), get_skill_id("TC-3.2"), weight=1)

net.add_edge(get_module_id("PROJ831a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("PROJ831a"), get_skill_id("IDU-2.1"), weight=1)

net.add_edge(get_module_id("INFO832a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO832a"), get_skill_id("IDU-3.1"), weight=1)

net.add_edge(get_module_id("INFO833a"), get_skill_id("IDU-1.1"), weight=1)
net.add_edge(get_module_id("INFO833a"), get_skill_id("IDU-1.2"), weight=1)
net.add_edge(get_module_id("INFO833a"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("INFO833a"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO833a"), get_skill_id("IDU-4.2"), weight=1)

net.add_edge(get_module_id("INFO834a"), get_skill_id("TC-3.2"), weight=1)
net.add_edge(get_module_id("INFO834a"), get_skill_id("TC-1.2"), weight=1)
net.add_edge(get_module_id("INFO834a"), get_skill_id("IDU-4.1"), weight=1)
net.add_edge(get_module_id("INFO834a"), get_skill_id("IDU-2.3"), weight=1)
net.add_edge(get_module_id("INFO834a"), get_skill_id("IDU-1.3"), weight=1)
net.add_edge(get_module_id("INFO834a"), get_skill_id("IDU-1.2"), weight=1)

net.add_edge(get_module_id("ISOC831a"), get_skill_id("TC-3.1"), weight=1)
net.add_edge(get_module_id("ISOC831a"), get_skill_id("TC-3.2"), weight=1)
